docs: add English README.md and CONTRIBUTING.md files
antvis/XFlow pull request #163
Opened 2022-03-02 20:51 UTC by cliffordfajardo

## What is the change?
- added English translation for `README.md` file
- added English translation for `CONTRIBUTING.md` file

## Why are we making this change?
- Help English speaking users understand what this library offers
- Helps browser search engines surface the XFlow library to English speaking population

2022-03-02 21:10 UTC, cliffordfajardo commented
@yn-boyu @lxfu1 - 
please feel free to make edit to my github code branch, github now has Codespaces enabled for nearly all repos on Github.com 🎉  
So you don't even need to run my code on your local computer since Codespaces allows you to edit in the browser now

I'm in the United States so it make take some time to make requested changes due to big time difference

"Allow edits from maintainers" is enabled ✔
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests


**My fork of XFlow: https://github.com/cliffordfajardo/XFlow**

![CleanShot 2022-03-02 at 13 09 42@2x](https://user-images.githubusercontent.com/6743796/156450143-d0d04feb-ea48-47f8-b3c4-e6e114359904.png)

2022-03-03 02:43 UTC, lyn-boyu requested changes
Thanks for your contribution

2022-03-03 02:43 UTC, lyn-boyu commented on README.md
> +### Step2 设置相关配置
this line is missing

2022-03-03 02:43 UTC, lyn-boyu commented on README.md
> +### Step3 画布渲染等逻辑操作
this line is missing

2022-03-03 02:43 UTC, lyn-boyu commented on README.md
> +设置相关配置后, 我们就可以在 `onLoad` 方法里进行一些必要的业务逻辑操作，比如从服务端获取数据、执行布局算法、渲染画布内容、监听画布相关事件等。
this line is missing

2022-03-03 02:43 UTC, lyn-boyu commented on README.md
> +├── packages
this line is missing

2022-03-03 04:30 UTC, cliffordfajardo commented
Ok will fix - thanks for the feedback

2022-03-03 05:49 UTC, gujinyue1010 reviewed
+1

2022-03-03 05:49 UTC, merged